-- searches through various schemas for a "VIEW_NAME" and returns name of a table that has the VIEW_NAME in it's DDL.
-- in other words looks for usage of a given view in downstream object's DDL

SET VIEW_NAME = '%QA_DWH.DOMAIN.DOCUMENT_SEASON_SUB_ORDER_TYPE_%';

SELECT
'QA_DWH.PRESENTATION' AS SCHEMA
, ALL_DDLS.VALUE
, ALL_DDLS.VALUE LIKE $VIEW_NAME  AS STRING_CONTAINS_MARKER  -- not perfect, I used semicolns in some comments, so can't use those either :/
, 'QA_DWH.PRESENTATION.' || REGEXP_SUBSTR(ALL_DDLS.VALUE, '(TABLE|VIEW|TASK) ([A-Z._]+)',1,1,'ime',2) TBL_NAME

FROM TABLE (SPLIT_TO_TABLE (GET_DDL ('SCHEMA', 'QA_DWH.PRESENTATION'), 'create')  ) AS ALL_DDLS
WHERE STRING_CONTAINS_MARKER

UNION ALL

SELECT
'QA_DWH.DOMAIN' AS SCHEMA
, ALL_DDLS.VALUE
, ALL_DDLS.VALUE LIKE $VIEW_NAME  AS STRING_CONTAINS_MARKER  -- not perfect, I used semicolns in some comments, so can't use those either :/
, 'QA_DWH.DOMAIN.' || REGEXP_SUBSTR(ALL_DDLS.VALUE, '(TABLE|VIEW|TASK) ([A-Z._]+)',1,1,'ime',2) TBL_NAME

FROM TABLE (SPLIT_TO_TABLE (GET_DDL ('SCHEMA', 'QA_DWH.DOMAIN'), 'create')  ) AS ALL_DDLS
WHERE STRING_CONTAINS_MARKER

UNION ALL

SELECT
'QA_DWH.CONFORMED' AS SCHEMA
, ALL_DDLS.VALUE
, ALL_DDLS.VALUE LIKE $VIEW_NAME  AS STRING_CONTAINS_MARKER  -- not perfect, I used semicolns in some comments, so can't use those either :/
, 'QA_DWH.CONFORMED.' || REGEXP_SUBSTR(ALL_DDLS.VALUE, '(TABLE|VIEW|TASK) ([A-Z._]+)',1,1,'ime',2) TBL_NAME

FROM TABLE (SPLIT_TO_TABLE (GET_DDL ('SCHEMA', 'QA_DWH.CONFORMED'), 'create')  ) AS ALL_DDLS
WHERE STRING_CONTAINS_MARKER

UNION ALL

SELECT
'PROD_DWH.PRESENTATION' AS SCHEMA
, ALL_DDLS.VALUE
, ALL_DDLS.VALUE LIKE $VIEW_NAME  AS STRING_CONTAINS_MARKER  -- not perfect, I used semicolns in some comments, so can't use those either :/
, 'PROD_DWH.PRESENTATION.' || REGEXP_SUBSTR(ALL_DDLS.VALUE, '(TABLE|VIEW|TASK) ([A-Z._]+)',1,1,'ime',2) TBL_NAME

FROM TABLE (SPLIT_TO_TABLE (GET_DDL ('SCHEMA', 'PROD_DWH.PRESENTATION'), 'create')  ) AS ALL_DDLS
WHERE STRING_CONTAINS_MARKER

UNION ALL

SELECT
'PROD_DWH.DOMAIN' AS SCHEMA
, ALL_DDLS.VALUE
, ALL_DDLS.VALUE LIKE $VIEW_NAME  AS STRING_CONTAINS_MARKER  -- not perfect, I used semicolns in some comments, so can't use those either :/
, 'PROD_DWH.DOMAIN.' || REGEXP_SUBSTR(ALL_DDLS.VALUE, '(TABLE|VIEW|TASK) ([A-Z._]+)',1,1,'ime',2) TBL_NAME

FROM TABLE (SPLIT_TO_TABLE (GET_DDL ('SCHEMA', 'PROD_DWH.DOMAIN'), 'create')  ) AS ALL_DDLS
WHERE STRING_CONTAINS_MARKER

UNION ALL

SELECT
'PROD_DWH.CONFORMED' AS SCHEMA
, ALL_DDLS.VALUE
, ALL_DDLS.VALUE LIKE $VIEW_NAME  AS STRING_CONTAINS_MARKER  -- not perfect, I used semicolns in some comments, so can't use those either :/
, 'PROD_DWH.CONFORMED.' || REGEXP_SUBSTR(ALL_DDLS.VALUE, '(TABLE|VIEW|TASK) ([A-Z._]+)',1,1,'ime',2) TBL_NAME

FROM TABLE (SPLIT_TO_TABLE (GET_DDL ('SCHEMA', 'PROD_DWH.CONFORMED'), 'create')  ) AS ALL_DDLS
WHERE STRING_CONTAINS_MARKER
;
